// Code generated by protoc-gen-go.
// source: qapp_package.proto
// DO NOT EDIT!

/*
Package codec is a generated protocol buffer package.

It is generated from these files:
	qapp_package.proto

It has these top-level messages:
	QAppRequest
	QAppResponse
	ExtInfo
	UserExtInfo
	HttpHeader
	Http
*/
package main

import "github.com/golang/protobuf/proto"
import "fmt"
import "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type QAppProtoErrCode int32

const (
	QAppProtoErrCode_QAPP_EC_OK             QAppProtoErrCode = 0
	QAppProtoErrCode_QAPP_EC_REQ_BAD_PKG    QAppProtoErrCode = 1
	QAppProtoErrCode_QAPP_EC_CMD_INVALID    QAppProtoErrCode = 2
	QAppProtoErrCode_QAPP_EC_PARAMS_INVALID QAppProtoErrCode = 3
	QAppProtoErrCode_QAPP_EC_INNER_ERROR    QAppProtoErrCode = 4
	QAppProtoErrCode_QAPP_EC_TIME_OUT       QAppProtoErrCode = 5
	QAppProtoErrCode_QAPP_EC_SERVER_BUSY    QAppProtoErrCode = 6
	QAppProtoErrCode_QAPP_EC_NO_RIGHT       QAppProtoErrCode = 7
	QAppProtoErrCode_QAPP_EC_LOGIN_VERIFY   QAppProtoErrCode = 8
)

var QAppProtoErrCode_name = map[int32]string{
	0: "QAPP_EC_OK",
	1: "QAPP_EC_REQ_BAD_PKG",
	2: "QAPP_EC_CMD_INVALID",
	3: "QAPP_EC_PARAMS_INVALID",
	4: "QAPP_EC_INNER_ERROR",
	5: "QAPP_EC_TIME_OUT",
	6: "QAPP_EC_SERVER_BUSY",
	7: "QAPP_EC_NO_RIGHT",
	8: "QAPP_EC_LOGIN_VERIFY",
}
var QAppProtoErrCode_value = map[string]int32{
	"QAPP_EC_OK":             0,
	"QAPP_EC_REQ_BAD_PKG":    1,
	"QAPP_EC_CMD_INVALID":    2,
	"QAPP_EC_PARAMS_INVALID": 3,
	"QAPP_EC_INNER_ERROR":    4,
	"QAPP_EC_TIME_OUT":       5,
	"QAPP_EC_SERVER_BUSY":    6,
	"QAPP_EC_NO_RIGHT":       7,
	"QAPP_EC_LOGIN_VERIFY":   8,
}

func (x QAppProtoErrCode) Enum() *QAppProtoErrCode {
	p := new(QAppProtoErrCode)
	*p = x
	return p
}
func (x QAppProtoErrCode) String() string {
	return proto.EnumName(QAppProtoErrCode_name, int32(x))
}
func (x *QAppProtoErrCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(QAppProtoErrCode_value, data, "QAppProtoErrCode")
	if err != nil {
		return err
	}
	*x = QAppProtoErrCode(value)
	return nil
}
func (QAppProtoErrCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type QAppRequest struct {
	Version          *uint32  `protobuf:"varint,1,opt,name=version,def=1" json:"version,omitempty"`
	AppName          *string  `protobuf:"bytes,2,opt,name=app_name" json:"app_name,omitempty"`
	Cmd              *string  `protobuf:"bytes,3,opt,name=cmd" json:"cmd,omitempty"`
	Seq              *uint64  `protobuf:"varint,4,opt,name=seq" json:"seq,omitempty"`
	ClientIp         *string  `protobuf:"bytes,5,opt,name=client_ip" json:"client_ip,omitempty"`
	ServiceIp        *string  `protobuf:"bytes,6,opt,name=service_ip" json:"service_ip,omitempty"`
	Business         *string  `protobuf:"bytes,7,opt,name=business" json:"business,omitempty"`
	AuthKey          []byte   `protobuf:"bytes,8,opt,name=auth_key" json:"auth_key,omitempty"`
	AuthType         *uint32  `protobuf:"varint,9,opt,name=auth_type" json:"auth_type,omitempty"`
	AuthIp           *string  `protobuf:"bytes,10,opt,name=auth_ip" json:"auth_ip,omitempty"`
	AuthAppid        *uint64  `protobuf:"varint,11,opt,name=auth_appid" json:"auth_appid,omitempty"`
	Uid              *uint64  `protobuf:"varint,12,opt,name=uid" json:"uid,omitempty"`
	Body             []byte   `protobuf:"bytes,13,opt,name=body" json:"body,omitempty"`
	TraceId          *string  `protobuf:"bytes,256,opt,name=trace_id" json:"trace_id,omitempty"`
	ExtInfo          *ExtInfo `protobuf:"bytes,257,opt,name=ext_info" json:"ext_info,omitempty"`
	SpanId           *uint32  `protobuf:"varint,258,opt,name=span_id" json:"span_id,omitempty"`
	ParentId         *uint32  `protobuf:"varint,259,opt,name=parent_id" json:"parent_id,omitempty"`
	TestEnv          *string  `protobuf:"bytes,260,opt,name=test_env" json:"test_env,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *QAppRequest) Reset()                    { *m = QAppRequest{} }
func (m *QAppRequest) String() string            { return proto.CompactTextString(m) }
func (*QAppRequest) ProtoMessage()               {}
func (*QAppRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_QAppRequest_Version uint32 = 1

func (m *QAppRequest) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return Default_QAppRequest_Version
}

func (m *QAppRequest) GetAppName() string {
	if m != nil && m.AppName != nil {
		return *m.AppName
	}
	return ""
}

func (m *QAppRequest) GetCmd() string {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return ""
}

func (m *QAppRequest) GetSeq() uint64 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

func (m *QAppRequest) GetClientIp() string {
	if m != nil && m.ClientIp != nil {
		return *m.ClientIp
	}
	return ""
}

func (m *QAppRequest) GetServiceIp() string {
	if m != nil && m.ServiceIp != nil {
		return *m.ServiceIp
	}
	return ""
}

func (m *QAppRequest) GetBusiness() string {
	if m != nil && m.Business != nil {
		return *m.Business
	}
	return ""
}

func (m *QAppRequest) GetAuthKey() []byte {
	if m != nil {
		return m.AuthKey
	}
	return nil
}

func (m *QAppRequest) GetAuthType() uint32 {
	if m != nil && m.AuthType != nil {
		return *m.AuthType
	}
	return 0
}

func (m *QAppRequest) GetAuthIp() string {
	if m != nil && m.AuthIp != nil {
		return *m.AuthIp
	}
	return ""
}

func (m *QAppRequest) GetAuthAppid() uint64 {
	if m != nil && m.AuthAppid != nil {
		return *m.AuthAppid
	}
	return 0
}

func (m *QAppRequest) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *QAppRequest) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *QAppRequest) GetTraceId() string {
	if m != nil && m.TraceId != nil {
		return *m.TraceId
	}
	return ""
}

func (m *QAppRequest) GetExtInfo() *ExtInfo {
	if m != nil {
		return m.ExtInfo
	}
	return nil
}

func (m *QAppRequest) GetSpanId() uint32 {
	if m != nil && m.SpanId != nil {
		return *m.SpanId
	}
	return 0
}

func (m *QAppRequest) GetParentId() uint32 {
	if m != nil && m.ParentId != nil {
		return *m.ParentId
	}
	return 0
}

func (m *QAppRequest) GetTestEnv() string {
	if m != nil && m.TestEnv != nil {
		return *m.TestEnv
	}
	return ""
}

type QAppResponse struct {
	Seq              *uint64  `protobuf:"varint,1,opt,name=seq" json:"seq,omitempty"`
	ErrCode          *uint32  `protobuf:"varint,2,opt,name=err_code" json:"err_code,omitempty"`
	ErrMsg           *string  `protobuf:"bytes,3,opt,name=err_msg" json:"err_msg,omitempty"`
	Body             []byte   `protobuf:"bytes,4,opt,name=body" json:"body,omitempty"`
	ExtInfo          *ExtInfo `protobuf:"bytes,5,opt,name=ext_info" json:"ext_info,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *QAppResponse) Reset()                    { *m = QAppResponse{} }
func (m *QAppResponse) String() string            { return proto.CompactTextString(m) }
func (*QAppResponse) ProtoMessage()               {}
func (*QAppResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *QAppResponse) GetSeq() uint64 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

func (m *QAppResponse) GetErrCode() uint32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *QAppResponse) GetErrMsg() string {
	if m != nil && m.ErrMsg != nil {
		return *m.ErrMsg
	}
	return ""
}

func (m *QAppResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *QAppResponse) GetExtInfo() *ExtInfo {
	if m != nil {
		return m.ExtInfo
	}
	return nil
}

type ExtInfo struct {
	Type             *uint32      `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Http             *Http        `protobuf:"bytes,2,opt,name=http" json:"http,omitempty"`
	Data             []byte       `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	UserExtInfo      *UserExtInfo `protobuf:"bytes,4,opt,name=user_ext_info" json:"user_ext_info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ExtInfo) Reset()                    { *m = ExtInfo{} }
func (m *ExtInfo) String() string            { return proto.CompactTextString(m) }
func (*ExtInfo) ProtoMessage()               {}
func (*ExtInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ExtInfo) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *ExtInfo) GetHttp() *Http {
	if m != nil {
		return m.Http
	}
	return nil
}

func (m *ExtInfo) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ExtInfo) GetUserExtInfo() *UserExtInfo {
	if m != nil {
		return m.UserExtInfo
	}
	return nil
}

type UserExtInfo struct {
	UidType          *uint32 `protobuf:"varint,1,opt,name=uid_type" json:"uid_type,omitempty"`
	Platform         *uint32 `protobuf:"varint,2,opt,name=platform" json:"platform,omitempty"`
	NotifyUid        *uint64 `protobuf:"varint,3,opt,name=notify_uid" json:"notify_uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserExtInfo) Reset()                    { *m = UserExtInfo{} }
func (m *UserExtInfo) String() string            { return proto.CompactTextString(m) }
func (*UserExtInfo) ProtoMessage()               {}
func (*UserExtInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UserExtInfo) GetUidType() uint32 {
	if m != nil && m.UidType != nil {
		return *m.UidType
	}
	return 0
}

func (m *UserExtInfo) GetPlatform() uint32 {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return 0
}

func (m *UserExtInfo) GetNotifyUid() uint64 {
	if m != nil && m.NotifyUid != nil {
		return *m.NotifyUid
	}
	return 0
}

type HttpHeader struct {
	Key              *string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value            *string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HttpHeader) Reset()                    { *m = HttpHeader{} }
func (m *HttpHeader) String() string            { return proto.CompactTextString(m) }
func (*HttpHeader) ProtoMessage()               {}
func (*HttpHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *HttpHeader) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *HttpHeader) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type Http struct {
	HttpStatus       *uint32       `protobuf:"varint,1,opt,name=http_status" json:"http_status,omitempty"`
	HttpHeader       []*HttpHeader `protobuf:"bytes,2,rep,name=http_header" json:"http_header,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Http) Reset()                    { *m = Http{} }
func (m *Http) String() string            { return proto.CompactTextString(m) }
func (*Http) ProtoMessage()               {}
func (*Http) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Http) GetHttpStatus() uint32 {
	if m != nil && m.HttpStatus != nil {
		return *m.HttpStatus
	}
	return 0
}

func (m *Http) GetHttpHeader() []*HttpHeader {
	if m != nil {
		return m.HttpHeader
	}
	return nil
}

func init() {
	proto.RegisterType((*QAppRequest)(nil), "codec.QAppRequest")
	proto.RegisterType((*QAppResponse)(nil), "codec.QAppResponse")
	proto.RegisterType((*ExtInfo)(nil), "codec.ExtInfo")
	proto.RegisterType((*UserExtInfo)(nil), "codec.UserExtInfo")
	proto.RegisterType((*HttpHeader)(nil), "codec.HttpHeader")
	proto.RegisterType((*Http)(nil), "codec.Http")
	proto.RegisterEnum("codec.QAppProtoErrCode", QAppProtoErrCode_name, QAppProtoErrCode_value)
}

func init() { proto.RegisterFile("qapp_package.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 621 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0xcd, 0x52, 0xdb, 0x30,
	0x10, 0xae, 0x13, 0x87, 0x38, 0xeb, 0x84, 0x0a, 0xc1, 0xb4, 0x6a, 0x4f, 0x69, 0x0e, 0x9d, 0xb4,
	0x07, 0x66, 0xca, 0xb1, 0xb7, 0x10, 0x5c, 0xf0, 0x00, 0x49, 0x30, 0x3f, 0x33, 0x9c, 0x34, 0x22,
	0x56, 0xc0, 0x03, 0xb1, 0x15, 0x49, 0xce, 0x90, 0x5b, 0xff, 0x9e, 0xb2, 0x4f, 0xd0, 0xc7, 0xe8,
	0x48, 0xb6, 0x19, 0x1f, 0x7a, 0xdc, 0x6f, 0xb5, 0xfb, 0xfd, 0xac, 0x0d, 0x78, 0xc5, 0x84, 0xa0,
	0x82, 0xcd, 0x1f, 0xd9, 0x3d, 0xdf, 0x17, 0x32, 0xd3, 0x19, 0x6e, 0xcd, 0xb3, 0x98, 0xcf, 0x07,
	0x7f, 0x1a, 0xe0, 0x5f, 0x8c, 0x84, 0x88, 0xf8, 0x2a, 0xe7, 0x4a, 0x63, 0x0c, 0xed, 0x35, 0x97,
	0x2a, 0xc9, 0x52, 0xe2, 0xf4, 0x9d, 0x61, 0xef, 0xab, 0xf3, 0x05, 0x23, 0xf0, 0xcc, 0x7c, 0xca,
	0x96, 0x9c, 0x34, 0xfa, 0xce, 0xb0, 0x83, 0x7d, 0x68, 0xce, 0x97, 0x31, 0x69, 0x56, 0x85, 0xe2,
	0x2b, 0xe2, 0xf6, 0x9d, 0xa1, 0x8b, 0x77, 0xa0, 0x33, 0x7f, 0x4a, 0x78, 0xaa, 0x69, 0x22, 0x48,
	0xcb, 0xf6, 0x31, 0x80, 0xe2, 0x72, 0x9d, 0xcc, 0xb9, 0xc1, 0xb6, 0x2c, 0x86, 0xc0, 0xbb, 0xcb,
	0x55, 0x92, 0x72, 0xa5, 0x48, 0xbb, 0x42, 0x58, 0xae, 0x1f, 0xe8, 0x23, 0xdf, 0x10, 0xaf, 0xef,
	0x0c, 0xbb, 0x66, 0x95, 0x45, 0xf4, 0x46, 0x70, 0xd2, 0x31, 0x62, 0xf0, 0x6b, 0x68, 0x5b, 0x28,
	0x11, 0x04, 0xaa, 0xdd, 0x16, 0x60, 0x42, 0x24, 0x31, 0xf1, 0xad, 0x04, 0x1f, 0x9a, 0x79, 0x12,
	0x93, 0xae, 0x2d, 0xba, 0xe0, 0xde, 0x65, 0xf1, 0x86, 0xf4, 0xca, 0x95, 0x9e, 0x96, 0xcc, 0x08,
	0x89, 0xc9, 0xf7, 0xc2, 0xca, 0x07, 0xf0, 0xf8, 0xb3, 0xa6, 0x49, 0xba, 0xc8, 0xc8, 0x0f, 0x03,
	0xf9, 0x07, 0xdb, 0xfb, 0x36, 0x9b, 0xfd, 0xe0, 0x59, 0x87, 0xe9, 0x22, 0xc3, 0x08, 0xda, 0x4a,
	0xb0, 0xd4, 0x0c, 0xfd, 0x6c, 0x58, 0x1d, 0x18, 0x3a, 0x82, 0x49, 0xeb, 0x32, 0x26, 0xbf, 0x0a,
	0xcc, 0xec, 0xe6, 0x4a, 0x53, 0x9e, 0xae, 0xc9, 0x6f, 0xbb, 0x7b, 0x90, 0x42, 0xb7, 0xc8, 0x56,
	0x89, 0x2c, 0x55, 0xbc, 0x4a, 0xca, 0xb1, 0xca, 0x10, 0x78, 0x5c, 0x4a, 0x6a, 0xa8, 0x48, 0xa3,
	0x72, 0x67, 0x90, 0xa5, 0xba, 0x2f, 0x93, 0xad, 0xc4, 0xbb, 0x56, 0x7c, 0xbf, 0xa6, 0xb4, 0xf5,
	0x3f, 0xa1, 0x83, 0x47, 0x68, 0x57, 0x9a, 0xbb, 0xe0, 0xda, 0xdc, 0xec, 0x11, 0xf1, 0x3b, 0x70,
	0x1f, 0xb4, 0x16, 0xa4, 0xf0, 0xe7, 0x97, 0x63, 0x27, 0x5a, 0x0b, 0xf3, 0x30, 0x66, 0x9a, 0x59,
	0xc6, 0x2e, 0xfe, 0x04, 0xbd, 0x5c, 0x71, 0x49, 0x5f, 0x88, 0x5c, 0x3b, 0x81, 0xcb, 0x89, 0x6b,
	0xc5, 0x65, 0x45, 0x16, 0x80, 0x5f, 0x2b, 0x8d, 0x9d, 0x3c, 0x89, 0x69, 0x8d, 0x14, 0x81, 0x27,
	0x9e, 0x98, 0x5e, 0x64, 0x72, 0x49, 0xaa, 0xd8, 0x20, 0xcd, 0x74, 0xb2, 0xd8, 0x50, 0x73, 0x20,
	0xc3, 0xe8, 0x0e, 0x86, 0x00, 0x46, 0xc7, 0x09, 0x67, 0x31, 0x97, 0x26, 0x21, 0xf3, 0x01, 0x38,
	0xd6, 0x7e, 0x0f, 0x5a, 0x6b, 0xf6, 0x94, 0x97, 0x1f, 0xdd, 0x60, 0x0c, 0xae, 0x55, 0xbc, 0x0b,
	0xbe, 0x31, 0x43, 0x95, 0x66, 0x3a, 0x57, 0x25, 0xd9, 0xc7, 0x12, 0x7c, 0xb0, 0x7b, 0x48, 0xa3,
	0xdf, 0x1c, 0xfa, 0x07, 0x3b, 0x35, 0xa3, 0x05, 0xc1, 0xe7, 0xbf, 0x0e, 0x20, 0x73, 0x93, 0x99,
	0xf9, 0x09, 0x02, 0x29, 0xc7, 0x59, 0xcc, 0xf1, 0x36, 0xc0, 0xc5, 0x68, 0x36, 0xa3, 0xc1, 0x98,
	0x4e, 0x4f, 0xd1, 0x2b, 0xfc, 0x16, 0x76, 0xab, 0x3a, 0x0a, 0x2e, 0xe8, 0xe1, 0xe8, 0x88, 0xce,
	0x4e, 0x8f, 0x91, 0x53, 0x6f, 0x8c, 0xcf, 0x8f, 0x68, 0x38, 0xb9, 0x19, 0x9d, 0x85, 0x47, 0xa8,
	0x81, 0xdf, 0xc3, 0x9b, 0xaa, 0x31, 0x1b, 0x45, 0xa3, 0xf3, 0xcb, 0x97, 0x5e, 0xb3, 0x3e, 0x14,
	0x4e, 0x26, 0x41, 0x44, 0x83, 0x28, 0x9a, 0x46, 0xc8, 0xc5, 0x7b, 0x46, 0x4a, 0xd1, 0xb8, 0x0a,
	0xcf, 0x03, 0x3a, 0xbd, 0xbe, 0x42, 0xad, 0xfa, 0xf3, 0xcb, 0x20, 0xba, 0x09, 0x22, 0x7a, 0x78,
	0x7d, 0x79, 0x8b, 0xb6, 0xea, 0xcf, 0x27, 0x53, 0x1a, 0x85, 0xc7, 0x27, 0x57, 0xa8, 0x8d, 0x09,
	0xec, 0x55, 0xe8, 0xd9, 0xf4, 0x38, 0x9c, 0xd0, 0x9b, 0x20, 0x0a, 0xbf, 0xdd, 0x22, 0xef, 0x5f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x52, 0x59, 0x91, 0xf6, 0x03, 0x00, 0x00,
}
